#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

### PATH ###
# Init PATH
export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
# Windows PATH
export SYSTEM32="/mnt/c/Windows/System32"
if [[ -d $SYSTEM32 ]]; then
  # Windows Apps
  export PATH="/mnt/c/Users/zarre/AppData/Local/Programs/Microsoft VS Code/bin:$SYSTEM32:$PATH"
fi
# Mac PATH
if [[ "$OSTYPE" == darwin* ]]; then
  # Homebrew curl
  export PATH="/usr/local/opt/curl/bin:$PATH"
fi
# Rust Cargo
export PATH="$HOME/.cargo/bin:$PATH"
# Java
export PATH="$HOME/.jenv/bin:$PATH"
### PATH ###

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL=$EDITOR
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{opt/coreutils/libexec/gnubin,bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Java Version Manager
eval "$(jenv init -)"

# Display for apps running in WSL2
SYSTEM32="/mnt/c/Windows/System32"
if [[ -d $SYSTEM32 ]]; then
  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2; exit;}'):0.0
  sudo /etc/init.d/dbus start &> /dev/null
fi
