#
# Defines environment variables.
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Default Path
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/home/bz/.gem/ruby/2.5.0/bin"

# Private envs
source $HOME/.zshprivate

# Python
export PYTHONPATH="/usr/bin"

